FROM ubuntu:latest
RUN apt update 
RUN apt install curl -y

RUN curl -L -o /usr/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

RUN chmod +x /usr/bin/kubectl