name: CI

on:
  schedule:
    - cron: "* * * * 2"
  push:
    branches:
      - 'main'
  pull_request: {}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push alpine-curl-kubectl
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dev-util"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-curl-kubectl:latest
      -
        name: Build and push alpine-gcloud-kubectl
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:dev-util"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-gcloud-kubectl:latest        