name: CI

on:
  schedule:
    - cron: "0 0 * * TUE"
  push:
    branches:
      - 'main'
  pull_request: {}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push alpine-curl-kubectl
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:dev-util"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-curl-kubectl:latest

      - name: Build and push ubuntu-curl-kubectl
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:ubuntu-util"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-curl-kubectl:latest

      - name: Build and push alpine-gcloud-kubectl
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:gcloud-sdk"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-gcloud-kubectl:latest    

      - name: Build and push fsc-fp-test
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:fsc-fp-test"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fsc-fp-test:latest

      - name: Build and push Carvel tools
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:carvel-image"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/carvel-image:latest
